server:
  port: 8081

person:
#  latName: xiaoxiao
  last-name: xiaoxiao
  age: 18
  boss: true
  birth: 2019/2/2
#  map:
#    key1: value1
#    key2: value2
  map: {k1: v1,k2: v2}
  list:
    - cat
    - dog
    - mat
  dog:
    name: 小狗
    age: 2